
all:
	gcc -o client4 client4.c chat.c -lpthread
	gcc -o client5 client5.c chat.c -lpthread
	gcc -o server4 server4.c chat.c -lpthread
	gcc -o server server.c chat.c -lpthread

clean:
	rm -rf	server server4 client4 client5
